package analyzer.dependencyanalyzer;

import java.util.Vector;

/**
 * Created on November 4, 2014 by Ellina.
 * XML Parser that reads an XML report generated by Classycle.
 * Retrieves the information from the report into objects.
 */

public class XmlParser{
	
	private Vector<ClassDependencyInfo> classVector = new Vector<ClassDependencyInfo>();	// vector of mockClass objects
	private Vector<PackageDependencyInfo> packageVector = new Vector<PackageDependencyInfo>(); // vector of mockPackage objects

	// Steps:
	// Create the DOM from a given XML file.
	// Parse the DOM and fill in dependency objects.
	// Stick objects together in a vector
	//		that can be later passed to the Data Aggregator.
	
	/**
	 * Status: in progress.
	 * Analyzes the xml file to gather info on class dependencies.
	 * Adds info on each class to the classVector.
	 */
	public void analyzeXmlClassInfo(){
		
	}
	
	/**
	 * Status: in progress.
	 * Analyzes the xml file to gather info on package dependencies.
	 * Adds info on each package to the packageVector.
	 */
	public void analyzeXmlPackageInfo(){
		
	}

}
